In [1]:
import numpy as np

In [221]:
def sigmoid(x):
    return 1/(1+np.exp(x))

In [205]:
class Dense:
    def __init__(self,activation,units):
        self.units = units
        self.activation = activation
    def relu(self,x):
        return max(0,x)

    def linear(self,x):
        return x

    def sigmoid(self,x):
        return 1/(1+np.exp(x))
    
    def forward(self,X):
        features = X.shape[1]
        X = X.T
        #weight and bias array initialization
        b = (np.ones(self.units) * 0.01).reshape(self.units,1)

        W = np.random.rand(self.units,features)
        
        
        result = np.dot(W,X) + b
        if self.activation =="relu":
            result = self.relu(result)
        elif self.activation =="linear":
            result = self.linear(result)
        else:
            
            result = self.sigmoid(result)
        return W,result,b

In [206]:
a = Dense("sigmoid",units =10)

In [207]:
X = np.random.rand(150,5)

In [208]:
weights, res,b_arr= a.forward(X)

In [209]:
res

array([[0.30510902, 0.06076458, 0.09846667, ..., 0.08611903, 0.16393348,
        0.12052649],
       [0.37277707, 0.12514145, 0.26379613, ..., 0.1244342 , 0.24805057,
        0.17917504],
       [0.30817424, 0.06058904, 0.09906559, ..., 0.09338537, 0.12747069,
        0.13966735],
       ...,
       [0.37898771, 0.15302568, 0.28826832, ..., 0.20980057, 0.29358524,
        0.23060197],
       [0.38747041, 0.18214627, 0.23556318, ..., 0.25295776, 0.27219218,
        0.27657343],
       [0.30442895, 0.05841563, 0.12384396, ..., 0.0925371 , 0.14561094,
        0.13910944]])

In [210]:
first = weights[0].reshape(1,5)

In [225]:
second = X[0].T.reshape(5,1)

In [226]:
sigmoid(np.dot(first,second) + 0.01)

array([[0.30510902]])

In [227]:
np.dot(first,second) +0.01

array([[0.8230858]])